dist:
  name: otelcol-custom
  output_path: ./bin

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.102.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.102.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.102.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.102.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/githubactionsjunitreceiver v0.102.0
    path: .

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.102.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.102.0
