receivers:
  githubactionsjunit:
    webhook_secret: ${env:WEBHOOK_SECRET}
    token: ${env:GITHUB_TOKEN}
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

extensions:
  pprof:
  zpages:
    endpoint: "localhost:55679"

exporters:
  debug:
    verbosity: basic
  file:
    path: /tmp/logs.txt

service:
  extensions: [zpages, pprof]
  pipelines:
    traces:
      receivers: [githubactionsjunit]
      processors: [batch]
      exporters: [debug, file]
  telemetry:
    logs:
      level: debug
